### ISSUE TITLE
Fails to build from source: '`#![feature]` may not be used on the stable release channel'.

### ISSUE THREAD

**Issue by dreirund** [LevitatingBusinessMan/openai-cli#1]
When building the software according to [&nearr;&hairsp;this recipe](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=openai-cli), it fails with the following error:

```
[...]
   Compiling reedline v0.17.0
   Compiling openai-cli v0.1.0 (/tmp/makepkg/build/openai-cli/src/openai-cli)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:1:12
  |
1 | #![feature(str_split_remainder)]
  |            ^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `openai-cli` due to previous error
```

`rustc --explain E0554` says:

> Feature attributes are only allowed on the nightly release channel. Stable or beta compilers will not comply.
> 
> Erroneous code example:
> 
> ```
> #![feature(lang_items)] // error: `#![feature]` may not be used on the
>                         //        stable release channel
> ```
> 
> If you need the feature, make sure to use a nightly release of the compiler (but be warned that the feature may be removed or altered in the future).

Note that I don't have knowledge of rust at all.

Regards!

**Comment by LevitatingBusinessMan** [comment]
Hey dreieck,

The feature I am using is only available on the nightly toolchain.

Use `cargo +nightly build` to build with nightly, it should work. (I think `cargo +nightly install openai-cli` should also work).

Thanks for trying out my software, I hope to add improvements soon like streaming responses and saving history.

I will make sure to update the documentation regarding the nightly toolchain.
